Add cache to inventory plugin (#275)
* Update icinga_director_inventory.py for icingadb

If the deprecated monitoring module is missing the inventory plugin 
 fails.
This adds a check for the icingadb module and improves host group handling by URL quoting and casting to safe group name.

* Add cache to icinga_director_inventory.py

Make optional usage of Ansible cache possible for this inventory plugin.

* fix  pep8 issue

ERROR: plugins/inventory/icinga_director_inventory.py:279:9: E303: too many blank lines (2) (100%)

---------

Co-authored-by: Martin Schurz <Martin.Schurz@telekom.de>