role: add check_command to icinga_service_apply (#161)
add the 'check_command' parameter to the 'icinga_service_apply' task.

This should be working according to the examples but is currently missing here which leads to the following error message:
```
Error: Validation failed for object 'service_apply_rule' of type 'Service'; Attribute 'check_command': Attribute must not be empty.
```